export const navbarClassname = {
  nav: [
    "flex",
    "justify-center",
    "font-medium",
    "w-full z-10 fixed top-0 rounded-md backdrop-blur-[6px] bg-opacity-10",
    "bg-[#272e36db]",
    "py-3",
    // "shadow-md",
  ].join(" "),
  header: [
    "flex",
    "font-medium",
    "justify-around",
    "w-[45%]",
    "items-center",
  ].join(" "),
  navLink: [
    // "rounded-md",
    // "p-2",
    "hover:text-secondary",
    "hover:transition-all",
    "hover:duration-300",
    // "text-lg ",
    // "hover:border",
    // "hover:shadow-[rgba(0,0,15,0.5)_3px_3px_3px_3px]",
    "hover:drop-shadow-[rgba(30,136,196,1)_1px_1px_10px] ",
    // "hover:text-xl",
  ].join(" "),
};
