export const navbarClassname = {
  nav: [
    "flex",
    "justify-center",
    "font-medium",
    "w-full",
    "z-10",
    "fixed",
    "top-0",
    "rounded-md",
    "backdrop-blur-[6px]",
    "bg-opacity-10",
    "bg-[#272e36db]",
    //"py-3",
    // "shadow-md",
  ].join(" "),
  navSmartphone: [
    "flex",
    "flex-col",
    "justify-around",
    "items-center",
    "w-full",
    "z-10",
    "fixed",
    "bottom-0",
    //"py-3",
    "bg-[#11151adb]",
    "rounded-md",
    "backdrop-blur-[6px]",
    "bg-opacity-10",
  ].join(" "),
  header: [
    //"w-[80%]",
    ////"border-t",
    //"border-t-[rgba(30,136,196,1)]",
    //"md:border-none",
    "w-full",
    "md:w-[45%]",
    "md:max-w-[33rem]",
    "flex",
    "justify-around",
    "items-center",
    "font-medium",
    "py-3",
  ].join(" "),
  navLink: [
    // "rounded-md",
    // "p-2",
    "hover:text-secondary",
    "hover:transition-all",
    "hover:duration-300",
    // "text-lg ",
    // "hover:border",
    // "hover:shadow-[rgba(0,0,15,0.5)_3px_3px_3px_3px]",
    "hover:drop-shadow-[rgba(30,136,196,1)_1px_1px_10px] ",
    // "hover:text-xl",
  ].join(" "),
};
