export const photoClassname = {
  main: [
    "flex",
    "flex-row-reverse",
    //"flex-col",
    // "gap-8",
    "items-center",
    "justify-between",
    // "text-center",
    "mt-8",
  ].join(" "),
  imgDiv: [
    "flex-none",
    "self-center",
    // "hidden",
    "flex",
  ].join(" "),
  img: [
    "w-20",
    "md:w-[5rem]",
    "rounded-full",
    "border-[1.5px]",
    // "shadow-lg",
    "shadow-[rgba(0,0,15,0.5)_1px_1px_10px_1px]",
  ].join(" "),
  secondary: [
    "flex",
    "gap-8",
    // "justify-center",
    "md:justify-start",
    "pb-2",
    // "md:mt-2",
  ].join(" "),
  name: [
    "md:text-4xl",
    "text-2xl",
    "text-nowrap",
    // "text-center",
    "font-bold",
    "tracking-wide",
  ].join(" "),
  title: [
    "text-secondary",
    "md:text-2xl",
    "text-xl",
    "font-medium",
    "tracking-wide",
  ].join(" "),
};
