export const photoClassname = {
  main: [
    "flex",
    "flex-col",
    "gap-4",
    "text-center",
    "mb-4",
  ].join(" "),
  imgDiv: [
    "flex-none",
    "self-center",
    // "hidden",
    "flex",
  ].join(" "),
  img: [
    "w-20",
    "md:w-24",
    "rounded-full",
    "border-[1.5px]",
    // "shadow-lg",
    "shadow-[rgba(0,0,15,0.5)_1px_1px_10px_1px]",
  ].join(" "),
  secondary: [
    "flex",
    "gap-8",
    "justify-center",
    "md:justify-start",
    "p-2",
    "md:mt-2",
  ].join(" "),
  name: [
    "md:text-5xl",
    "text-3xl",
    "text-center",
    "font-bold",
    "tracking-wide",
  ].join(" "),
  title: [
    "text-secondary",
    "md:text-4xl",
    "text-xl",
    "font-medium",
    "tracking-wide",
  ].join(" "),
};
