export const projectsClassname = {
  main: [
    "flex",
    "flex-row",
    "items-center",
    "text-center",
    "flex-wrap",
    "md:justify-between",
    "gap-12",
    "justify-center",
    "pb-20",
  ].join(" "),
  singleProj: [
    "parent",
    "md:w-[45%]",
    "w-[75%]",
    "flex",
    "flex-col",
    "gap-2",
  ].join(" "),
  img: ["w-40", "h-40", "object-cover"].join(" "),
  projectDiv: [
    "mt-2",
    "flex",
    "gap-2",
    "items-center",
    "justify-center",
  ].join(" "),
  title: [
    "text-center",
    "text-nowrap",
    "px-3",
    "py-1",
    // "m-4",
    "text-secondary",
    "font-semibold",
    "text-xl",
    "rounded-md",
    "border",
    "shadow-[rgba(0,0,0,0.322)_3px_3px_3px_3px]",
    "hover:shadow-[rgba(0,0,15,0.5)_3px_3px_3px_3px]",
    "hover:text-white",
    "hover:bg-secondary",
    "hover:transition-all",
    "hover:duration-300",
  ].join(" "),
  state: ["text-tertiary font-light"].join(" "),
  divider: [
    "w-10",
    "h-1",
    "mt-1",
    "self-center",
    "bg-white",
    "border-0",
    "rounded-sm",
    "bg-opacity-40",
  ].join(" "),
};
