export const projectsClassname = {
  main: [
    "flex",
    "flex-row",
    "items-center",
    "text-center",
    "flex-wrap",
    "justify-between",
    "gap-12",
  ].join(" "),
  singleProj: ["parent", "w-[45%]", "flex", "flex-col", "gap-2"].join(" "),
  title: [
    "text-center",
    "text-nowrap",
    "px-3",
    "py-1",
    "m-4",
    "text-secondary",
    "font-semibold",
    "text-lg",
    "rounded-sm",
    "hover:text-white",
    "hover:bg-secondary",
    "hover:transition-all",
    "hover:duration-300",
  ].join(" "),
  state: ["text-tertiary"].join(" "),
  divider: [
    "w-10",
    "h-1",
    "self-center",
    "bg-white",
    "border-0",
    "rounded-sm",
    "bg-opacity-40",
  ].join(" "),
};
